//---------------------------------------------------
//         *****!Do not edit this file!*****
//---------------------------------------------------
//   ___ _        _          __  __
//  | __(_)_ _ __| |_       |  \/  |__ _ _ __
//  | _|| | '_(_-<  _|      | |\/| / _` | '_ \
//  |_| |_|_| /__/\__|      |_|  |_\__,_| .__/
//           | |   ___  __ _ __| (_)    |_|
//           | |__/ _ \/ _` / _` |_|
//           |____\___/\__,_\__,_(_)
//---------------------------------------------------
// Purpose: Only runs on first map load of session
//---------------------------------------------------

// Reset dev level
if (Config_DevMode) {
    EntFire("p2mm_servercommand", "command", "developer 1")
}
else {
    EntFire("p2mm_servercommand", "command", "clear; developer 0")
}

if (!PluginLoaded) {
    // Remove Portal Gun (Map transition will sound less abrupt)
    Entities.CreateByClassname("info_target").__KeyValueFromString("targetname", "supress_blue_portalgun_spawn")
    Entities.CreateByClassname("info_target").__KeyValueFromString("targetname", "supress_orange_portalgun_spawn")

    EntFire("p2mm_servercommand", "command", "script printl(\"(P2:MM): Attempting to load the P2:MM plugin...\")", 0.03)
    EntFire("p2mm_servercommand", "command", "plugin_load 32pmod", 0.05)
}

// Facilitate first load after game launch
function MakeProgressCheck() {
    printl("(P2:MM): First map load detected! Attempting to reset map...")
    local ChangeToThisMap = "mp_coop_start"
    for (local course = 1; course <= 6; course++) {
        // 9 levels is the highest that a course has
        for (local level = 1; level <= 9; level++) {
            if (IsLevelComplete(course - 1, level - 1)) {
                ChangeToThisMap = "mp_coop_lobby_3"
            }
        }
    }
    EntFire("p2mm_servercommand", "command", "stopvideos; changelevel " + ChangeToThisMap, 0)
}

// Even if the plugin was already loaded, we need
// to reset the map anyways to check the progress
EntFire("p2mm_servercommand", "command", "script MakeProgressCheck()", 1) // Must be delayed
