//---------------------------------------------------
//         *****!Do not edit this file!*****
//---------------------------------------------------
//   ___  ___  _  __  __  __  __                   
//  | _ \|_  )(_)|  \/  ||  \/  |                  
//  |  _/ / /  _ | |\/| || |\/| |                  
//  |_|__/___|(_)|_|  |_||_|  |_|                  
//   / __| ___  __| | ___                          
//  | (__ / _ \/ _` |/ -_)                         
//  _\___|\___/\__,_|\___|     _     _           _ 
//  \ \ / /__ _  _ _ (_) __ _ | |__ | | ___  ___(_)
//   \ V // _` || '_|| |/ _` || '_ \| |/ -_)(_-< _ 
//    \_/ \__,_||_|  |_|\__,_||_.__/|_|\___|/__/(_)
//---------------------------------------------------
// Purpose: Here, we declare and set up almost
// every variable used throughout the P2:MM codebase.
//---------------------------------------------------

//---------------
// Classes
//---------------
GlobalSpawnClass <- class {
    // Try To Make All Spawns Global
    useautospawn = false
    // Use Set Spawnpoint
    usesetspawn = false

    // Set SpawnPoint
    setspawn = class {
        // Set SpawnPoint
        position = Vector(0,0,0)
        // Set Radius
        radius = 0
    }

    // Reds Spawn Parameters
    red = class {
        spawnpoint = Vector(0,0,0)
        rotation = Vector(0,0,0)
        velocity = Vector(0,0,0)
    }
    // Blues Spawn Parameters
    blue = class {
        spawnpoint = Vector(0,0,0)
        rotation = Vector(0,0,0)
        velocity = Vector(0,0,0)
    }
}

//---------------
// Booleans
//---------------
IsOnSingleplayerMaps <- false
if (GetMapName().len() >= 7 && GetMapName().slice(0,7) != "mp_coop") {
    IsOnSingleplayerMaps = true
}
CanCheckAngle <- false
CanHook <- false
CheatsOn <- false

DevModeConfig <- Config_DevMode

DoneCacheing <- false
DoneWaiting <- false
fogs <- false
GlobalOverridePluginGrabController <- true // By default unless specified in mapsupport
HasSpawned <- false
MadeSpawnClass <- false
OrangeCacheFailed <- false
Player2Joined <- false
PostMapLoadDone <- false
PermaPotato <- false
StartDevModeCheck <- false
usefogcontroller <- false

//---------------
// Ints/Floats
//---------------
amtoffsetclr <- 0
cacheoriginalplayerposition <- 0
EntityCap <- 2000
EntityCapLeeway <- 20
FailsafeEntityCap <- 2010
PlayerID <- 0
PreviousNametagItter <- 0
PreviousTime1Sec <- 0
PreviousTime5Sec <- 0
randomportalsize <- 34 // Used if Config_RandomPortalSize is true
randomportalsizeh <- 34 // Used if Config_RandomPortalSize is true
TickSpeed <- 0.00
TotalRemovedEnts <- 0

//---------------
// Arrays/Tables
//---------------
ConsoleAscii <- [
""
"██████╗░░█████╗░██████╗░████████╗░█████╗░██╗░░░░░░░░░░██████╗░"
"██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝██╔══██╗██║░░░░░░░░░░╚════██╗"
"██████╔╝██║░░██║██████╔╝░░░██║░░░███████║██║░░░░░░░░░░░░███╔═╝"
"██╔═══╝░██║░░██║██╔══██╗░░░██║░░░██╔══██║██║░░░░░░░░░░██╔══╝░░"
"██║░░░░░╚█████╔╝██║░░██║░░░██║░░░██║░░██║███████╗░░░░░███████╗"
"╚═╝░░░░░░╚════╝░╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░╚═╝╚══════╝░░░░░╚══════╝"
""
"░░░░░░███╗░░░███╗██████╗░░░░░███╗░░░███╗░█████╗░██████╗░░░░░░░"
"░░░░░░████╗░████║██╔══██╗░░░░████╗░████║██╔══██╗██╔══██╗░░░░░░"
"░░░░░░██╔████╔██║██████╔╝░░░░██╔████╔██║██║░░██║██║░░██║░░░░░░"
"░░░░░░██║╚██╔╝██║██╔═══╝░░░░░██║╚██╔╝██║██║░░██║██║░░██║░░░░░░"
"░░░░░░██║░╚═╝░██║██║░░░░░░░░░██║░╚═╝░██║╚█████╔╝██████╔╝░░░░░░"
"░░░░░░╚═╝░░░░░╚═╝╚═╝░░░░░░░░░╚═╝░░░░░╚═╝░╚════╝░╚═════╝░░░░░░░"
""
]
CurrentlyDead <- []
entityclasses <- []
EventList <- []
ExpendableEntities <- [
    "logic_auto",
    "logic_autosave",
    "env_viewpunch",
    "env_shake",
    "info_particle_system",
    "env_fog_controller",
    "env_fade",
    "func_areaportal",
    "env_soundscape",
    "ambient_generic",
    "prop_physics_paintable",
    "prop_physics",
    "prop_physics_override",
    "prop_physics_multiplayer",
    "prop_detail",
    "prop_dynamic_ornament",
    "prop_dynamic_override",
    "func_illusionary",
    "func_brush",
    "prop_weighted_cube",
    "func_detail",
]
InvalidRootMoveParents <- [
    "player",
    "prop_portal",
    "worldspawn",
    ""
]
MPMCoopCreditNames <- [ // Add names to coop credits map
    "### ",
    "### ",
    "### ",
    "### ",
    "###Portal 2: Multiplayer Mod ~ Credits",
    "### ",
    "###--------------------------",
    "###P2:MM Head Creators",
    "###--------------------------",
    "kyleraykbs | Team Lead + Script + Launcher",
    "Nanoman2525 | Mapping + Entity Work + Launcher + Script",
    "Vista | Reverse Engineering, Plugin Developer",
    "Bumpy | Script Theory",
    "Wolƒe Strider Shoσter | Singleplayer Support",
    "cabiste | Scripting + Mod Launcher + Code Refactor",
    "###--------------------------",
    "###P2:MM Team Members",
    "###--------------------------",
    "sear | Speedrun Mode Ideas",
    "Jeffrey | Previous Code Cleanup",
    "###--------------------------",
    "###P2:MM Contributers",
    "###--------------------------",
    "Dreadnox | Speedrun Mode Ideas",
    "Enator18 | Python Dev"
    "Blub/Vecc | Previous Code Commenting",
    "Darnias | Jumpstarter Code",
    "PieCreeper | Promotion of the mod",
    "###--------------------------",
    "###Special Thanks To:",
    "###--------------------------",
    "SuperSpeed",
    "Mystical Ace",
    "ANotSoSpookySkeleton",
    "Panter",
    "tnp|\\n|thewoodster75",
    "ThePineapple",
    "Areng",
    "SuperSpeed",
    "Brawler",
    "X man",
    "###--------------------------",
    "###Valve: Credits",
    "###--------------------------",
]
mpcoursenames <- [
    "mp_coop_doors",
    "mp_coop_fling_3",
    "mp_coop_wall_intro",
    "mp_coop_tbeam_redirect",
    "mp_coop_paint_come_along",
    "mp_coop_separation_1",
]
playerclasses <- []
spchapternames <- [
    "sp_a1_intro1",
    "sp_a2_laser_intro",
    "sp_a2_sphere_peek",
    "sp_a2_column_blocker",
    "sp_a2_bts3",
    "sp_a3_00",
    "sp_a3_speed_ramp",
    "sp_a4_intro",
    "sp_a4_finale1"
]

//---------------
// Others
//---------------
OriginalAngle <- null
OriginalPosMain <- null