"Resource/UI/PluginMenu.res"
{
	"PluginMenu"
	{
		"ControlName"		"CPluginMenu"
		"fieldName"		"PluginMenu"
		"xpos"		"20"
		"ypos"		"60"
		"wide"		"600"
		"tall"		"350"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"text"
	{
		"ControlName"		"Label"
		"fieldName"		"Text"
		"xpos"		"350"
		"ypos"		"10"
		"wide"		"250"
		"tall"		"50"
		"autoResize"		"3"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"1"
		"tabPosition"		"0"
		"maxchars"		"-1"
		"textAlignment"		"north-west"
	}
	"option1"
	{
		"ControlName"		"Button"
		"fieldName"		"option1"
		"xpos"		"20"
		"ypos"		"30"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option1"
		"Default"		"1"
	}
	"option2"
	{
		"ControlName"		"Button"
		"fieldName"		"option2"
		"xpos"		"20"
		"ypos"		"60"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option2"
		"Default"		"0"
	}
	"option3"
	{
		"ControlName"		"Button"
		"fieldName"		"option3"
		"xpos"		"20"
		"ypos"		"90"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option3"
		"Default"		"0"
	}
	"option4"
	{
		"ControlName"		"Button"
		"fieldName"		"option4"
		"xpos"		"20"
		"ypos"		"120"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"4"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option4"
		"Default"		"0"
	}
	"option5"
	{
		"ControlName"		"Button"
		"fieldName"		"option5"
		"xpos"		"20"
		"ypos"		"150"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"5"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option5"
		"Default"		"0"
	}
	"option6"
	{
		"ControlName"		"Button"
		"fieldName"		"option6"
		"xpos"		"20"
		"ypos"		"180"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"6"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option6"
		"Default"		"0"
	}
	"option7"
	{
		"ControlName"		"Button"
		"fieldName"		"option7"
		"xpos"		"20"
		"ypos"		"210"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"7"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option7"
		"Default"		"0"
	}
	"option8"
	{
		"ControlName"		"Button"
		"fieldName"		"option8"
		"xpos"		"20"
		"ypos"		"240"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"8"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option8"
		"Default"		"0"
	}
	"option9"
	{
		"ControlName"		"Button"
		"fieldName"		"option9"
		"xpos"		"20"
		"ypos"		"270"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"8"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option9"
		"Default"		"0"
	}
	"option10"
	{
		"ControlName"		"Button"
		"fieldName"		"option10"
		"xpos"		"20"
		"ypos"		"300"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"8"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option10"
		"Default"		"0"
	}
	"option11"
	{
		"ControlName"		"Button"
		"fieldName"		"option11"
		"xpos"		"130"
		"ypos"		"30"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option11"
		"Default"		"1"
	}
	"option12"
	{
		"ControlName"		"Button"
		"fieldName"		"option12"
		"xpos"		"130"
		"ypos"		"60"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option12"
		"Default"		"0"
	}
	"option13"
	{
		"ControlName"		"Button"
		"fieldName"		"option13"
		"xpos"		"130"
		"ypos"		"90"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option13"
		"Default"		"0"
	}
	"option14"
	{
		"ControlName"		"Button"
		"fieldName"		"option14"
		"xpos"		"130"
		"ypos"		"120"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"4"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option14"
		"Default"		"0"
	}
	"option15"
	{
		"ControlName"		"Button"
		"fieldName"		"option15"
		"xpos"		"130"
		"ypos"		"150"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"5"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option15"
		"Default"		"0"
	}
	"option16"
	{
		"ControlName"		"Button"
		"fieldName"		"option16"
		"xpos"		"130"
		"ypos"		"180"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"6"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option16"
		"Default"		"0"
	}
	"option17"
	{
		"ControlName"		"Button"
		"fieldName"		"option17"
		"xpos"		"130"
		"ypos"		"210"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"7"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option17"
		"Default"		"0"
	}
	"option18"
	{
		"ControlName"		"Button"
		"fieldName"		"option18"
		"xpos"		"130"
		"ypos"		"240"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"8"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option18"
		"Default"		"0"
	}
	"option19"
	{
		"ControlName"		"Button"
		"fieldName"		"option19"
		"xpos"		"130"
		"ypos"		"270"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"8"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option19"
		"Default"		"0"
	}
	"option20"
	{
		"ControlName"		"Button"
		"fieldName"		"option20"
		"xpos"		"130"
		"ypos"		"300"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"8"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option20"
		"Default"		"0"
	}
	"option21"
	{
		"ControlName"		"Button"
		"fieldName"		"option21"
		"xpos"		"240"
		"ypos"		"30"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option21"
		"Default"		"1"
	}
	"option22"
	{
		"ControlName"		"Button"
		"fieldName"		"option22"
		"xpos"		"240"
		"ypos"		"60"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option22"
		"Default"		"0"
	}
	"option23"
	{
		"ControlName"		"Button"
		"fieldName"		"option23"
		"xpos"		"240"
		"ypos"		"90"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option23"
		"Default"		"0"
	}
	"option24"
	{
		"ControlName"		"Button"
		"fieldName"		"option24"
		"xpos"		"240"
		"ypos"		"120"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"4"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option24"
		"Default"		"0"
	}
	"option25"
	{
		"ControlName"		"Button"
		"fieldName"		"option25"
		"xpos"		"240"
		"ypos"		"150"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"5"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option25"
		"Default"		"0"
	}
	"option26"
	{
		"ControlName"		"Button"
		"fieldName"		"option26"
		"xpos"		"240"
		"ypos"		"180"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"6"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option26"
		"Default"		"0"
	}
	"option27"
	{
		"ControlName"		"Button"
		"fieldName"		"option27"
		"xpos"		"240"
		"ypos"		"210"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"7"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option27"
		"Default"		"0"
	}
	"option28"
	{
		"ControlName"		"Button"
		"fieldName"		"option28"
		"xpos"		"240"
		"ypos"		"240"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"8"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option28"
		"Default"		"0"
	}
	"option29"
	{
		"ControlName"		"Button"
		"fieldName"		"option29"
		"xpos"		"240"
		"ypos"		"270"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"8"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option29"
		"Default"		"0"
	}
	"option30"
	{
		"ControlName"		"Button"
		"fieldName"		"option30"
		"xpos"		"240"
		"ypos"		"300"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"8"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option30"
		"Default"		"0"
	}
	"option31"
	{
		"ControlName"		"Button"
		"fieldName"		"option31"
		"xpos"		"350"
		"ypos"		"270"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"8"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option31"
		"Default"		"0"
	}
	"option32"
	{
		"ControlName"		"Button"
		"fieldName"		"option32"
		"xpos"		"350"
		"ypos"		"300"
		"wide"		"100"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"8"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"option32"
		"Default"		"0"
	}
}
