#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'
color () { printf ${!1}; }

cat p232ascii
echo
echo
color NC

color BLUE

echo "Your local ip:" `ip route | grep '^default' | grep 'src' | awk '{print $(NF-2)}'`
echo "Your public ip:" `curl -s "http://api.ipify.org/"`

WINDOWED=""

read -p "Do you want to run the game in windowed mode? [y/n]" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
	WINDOWED="-window -w 1280 -h 720"
fi

echo "Backing up orignal files..."

mv "portal2/bin/linux32/server.so" "portal2/bin/linux32/server.so.orig"
mv "portal2/scripts/vscripts/mapspawn.nut" "portal2/scripts/vscripts/mapspawn.nut.orig"
mv "portal2/media/coop_bluebot_load.bik" "portal2/media/coop_bluebot_load.bik.orig"
mv "portal2/media/coop_orangebot_load.bik" "portal2/media/coop_orangebot_load.bik.orig"

echo "Copying files..."

cp -rf "portal2/MultiplayerModFiles/cfg" "portal2"
cp -rf "portal2/MultiplayerModFiles/media" "portal2"
cp -rf "portal2/MultiplayerModFiles/scripts" "portal2"
cp -r "portal2/bin/linux32/server.so.patched" "portal2/bin/linux32/server.so"

echo "Running game..."
color NC
./portal2.sh -game portal2 $WINDOWED -novid -allowspectators +exec multiplayermod.cfg +sv_lan 0 +mp_wait_for_other_player_notconnecting_timeout 240 +mp_wait_for_other_player_timeout 240 +map mp_coop_lobby_3 -nosixense

color BLUE

echo "Moving back original files..."

mv "portal2/bin/linux32/server.so.orig" "portal2/bin/linux32/server.so"
mv "portal2/scripts/vscripts/mapspawn.nut.orig" "portal2/scripts/vscripts/mapspawn.nut"
mv "portal2/media/coop_bluebot_load.bik.orig" "portal2/media/coop_bluebot_load.bik"
mv "portal2/media/coop_orangebot_load.bik.orig" "portal2/media/coop_orangebot_load.bik"

color NC